backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "page.njk" }
      - label: "Components"
        name: "components"
        widget: "list"
        types:
          - label: "Hero Banner"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Type", name: "type", widget: "select", options: ["image", "video"] }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "text" }
              - { label: "Image", name: "image", widget: "image", required: false }
              - { label: "Video URL", name: "videoUrl", widget: "string", required: false }
              - { label: "Full Height", name: "fullHeight", widget: "boolean", default: false }
              - label: "CTA"
                name: "cta"
                widget: "object"
                fields:
                  - { label: "Text", name: "text", widget: "string" }
                  - { label: "URL", name: "url", widget: "string" }
          
          - label: "Page Title"
            name: "pageTitle"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "text" }
          
          - label: "Markdown Block"
            name: "markdown"
            widget: "object"
            fields:
              - { label: "Content", name: "content", widget: "markdown" }
          
          - label: "Two Images"
            name: "twoImages"
            widget: "object"
            fields:
              - { label: "First Image", name: "first", widget: "image" }
              - { label: "First Image Alt", name: "firstAlt", widget: "string" }
              - { label: "Second Image", name: "second", widget: "image" }
              - { label: "Second Image Alt", name: "secondAlt", widget: "string" }
          
          - label: "Image and Markdown"
            name: "imageMarkdown"
            widget: "object"
            fields:
              - { label: "Image Position", name: "imagePosition", widget: "select", options: ["left", "right"] }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Image Alt", name: "imageAlt", widget: "string" }
              - { label: "Content", name: "content", widget: "markdown" }
          
          - label: "Three Columns"
            name: "threeColumns"
            widget: "object"
            fields:
              - label: "Columns"
                name: "columns"
                widget: "list"
                fields:
                  - { label: "Content", name: "content", widget: "markdown" }
                max: 3
          
          - label: "Gallery"
            name: "gallery"
            widget: "object"
            fields:
              - label: "Images"
                name: "images"
                widget: "list"
                fields:
                  - { label: "Image", name: "url", widget: "image" }
                  - { label: "Alt Text", name: "alt", widget: "string" }
          
          - label: "Two Columns"
            name: "twoColumns"
            widget: "object"
            fields:
              - label: "Columns"
                name: "columns"
                widget: "list"
                fields:
                  - { label: "Content", name: "content", widget: "markdown" }
                max: 2
          
          - label: "Lead Magnet"
            name: "leadMagnet"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Button Text", name: "buttonText", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Image Alt", name: "imageAlt", widget: "string" }

      - { label: "SEO Description", name: "description", widget: "text" }

  - name: "posts"
    label: "Blog Posts"
    folder: "src/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - label: "Components"
        name: "components"
        widget: "list"
        types:
          - label: "Markdown Block"
            name: "markdown"
            widget: "object"
            fields:
              - { label: "Content", name: "content", widget: "markdown" }
          
          - label: "Two Images"
            name: "twoImages"
            widget: "object"
            fields:
              - { label: "First Image", name: "first", widget: "image" }
              - { label: "First Image Alt", name: "firstAlt", widget: "string" }
              - { label: "Second Image", name: "second", widget: "image" }
              - { label: "Second Image Alt", name: "secondAlt", widget: "string" }
          
          - label: "Image and Markdown"
            name: "imageMarkdown"
            widget: "object"
            fields:
              - { label: "Image Position", name: "imagePosition", widget: "select", options: ["left", "right"] }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Image Alt", name: "imageAlt", widget: "string" }
              - { label: "Content", name: "content", widget: "markdown" }
          
          - label: "Lead Magnet"
            name: "leadMagnet"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Button Text", name: "buttonText", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Image Alt", name: "imageAlt", widget: "string" }
      
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "settings"
    label: "Settings"
    files:
      - name: "site"
        label: "Site Settings"
        file: "src/_data/site.json"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - { label: "Site Description", name: "description", widget: "text" }
          - { label: "Site URL", name: "url", widget: "string" }
          - label: "Social Media"
            name: "social"
            widget: "object"
            fields:
              - { label: "Twitter URL", name: "twitter", widget: "string" }
              - { label: "Twitter Handle", name: "twitterHandle", widget: "string" }
              - { label: "Instagram URL", name: "instagram", widget: "string" }
              - { label: "Instagram Handle", name: "instagramHandle", widget: "string" }
              - { label: "LinkedIn URL", name: "linkedin", widget: "string" }
              - { label: "LinkedIn Handle", name: "linkedinHandle", widget: "string" }
          - label: "Popup Settings"
            name: "popup"
            widget: "object"
            fields:
              - { label: "Enable Popup", name: "enabled", widget: "boolean", default: true }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "markdown" }
              - { label: "Button Text", name: "buttonText", widget: "string" }
              - { label: "Delay (in seconds)", name: "delay", widget: "number", default: 5 }
              - { label: "Show Once Per Session", name: "showOnce", widget: "boolean", default: true }
          - label: "Cookie Consent"
            name: "cookieConsent"
            widget: "object"
            fields:
              - { label: "Enable Cookie Banner", name: "enabled", widget: "boolean", default: true }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "markdown" }
              - { label: "Accept Button Text", name: "acceptText", widget: "string" }
              - { label: "Decline Button Text", name: "declineText", widget: "string" }